### PR TITLE
Induction record processing

### PR DESCRIPTION
**Pull request by tonyheadford**
We've spiked this idea for a way to process induction records from ECF1 and it seems like a good enough approach to build upon. 
This PR adds the basis of the induction record sanitizer and a service to extract school periods from those induction records which could be followed for extracting other period data from a ECF1 induction records.

### CODE REVIEW

**Comment by gracecbrennan** [comment]
This is ongoing - has chatted with Pete and Lorenzo on it already

**Comment by gracecbrennan** [comment]
@tonyheadford will be picking this back up today

**Comment by gracecbrennan** [comment]
Going to try to get this working in migration environ.

**Comment by gracecbrennan** [comment]
Getting together with Pete this afternoon to look at sorting things out in migration

**Comment by claire-hughez** [comment]
Tony will catch up on this. He's on support this week so his work on ECF2 will be limited.

**Comment by claire-hughez** [comment]
Tony will try and run the migration in the migration environment and see what happens. Managed to get through all of the support tickets yesterday!!! But already some new ones to deal with in ECF1.

**Review by peteryates — APPROVED** [review]
This looks great. It would be really useful as an extension if the output from these comparisons could be viewed (like in that branch I was messing around with a couple of weeks ago that had side-by-side comparisons).

**Comment by tonyheadford** [comment]
> This looks great. It would be really useful as an extension if the output from these comparisons could be viewed (like in that branch I was messing around with a couple of weeks ago that had side-by-side comparisons).

Yes agree

**Pull request merged**
