### PR TITLE
[750]: wrap register-ect journey routes into their own namespace

### PR DESCRIPTION
**Pull request by ltello**
[Ticket](https://github.com/DFE-Digital/register-early-career-teachers/issues/750)

To prevent clashes with the steps to register a mentor, this PR wraps the paths of the steps of the existing register-ect journey into its own segment.

From this:
```
/schools/what-you-will-need
/schools/find-ect
/schools/review-ect-details
/schools/check-answers
/schools/email-address
...
/schools/confirmation
``` 

To this:

```
/schools/register-ect/what-you-will-need
/schools/register-ect/find-ect
/schools/register-ect/review-ect-details
/schools/register-ect/check-answers
/schools/register-ect/email-address
...
/schools/register-ect/confirmation
```

### CODE REVIEW

**Review by TobyRet — COMMENTED** [review]
The intention behind this PR makes sense however I think we need to chat to whoever is [maintaining this spreadsheet with routes](https://educationgovuk.sharepoint.com/:x:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B0C1578EA-6431-47B2-9357-C7F610EE178F%7D&file=Register%20ECTs%20page%20titles%20and%20URLs.xlsx&action=default&mobileredirect=true) - I notice for example that there is no schools or register_ect namespace

**Comment by ltello** [comment]
Hey @TobyRet, as we have agreed this namespaced paths, please, can you re-review this PR?

**Review by peteryates — APPROVED** [review]
Looks good. We can leave the jump to resourceful routes until later 😄

**Comment by ltello** [comment]
Absolutely not. I just focused on keeping the existing url_helpers for the journey and didn't take the resourceful approach into account that even though it results in slightly different url helpers, I think it is much more appropriate.
Thanks!  Amended!

**Review by peteryates — APPROVED** [review]

**Pull request merged**
